---
title: "CemiTool"
editor_options: 
  chunk_output_type: console
---

```{r Load libraries}
library(here)
library(CEMiTool)
library(tidyverse)
```

```{r Load files}
# Phenodata
pheno <- read.delim(here("data", "phenodata_revision.tsv")) %>% 
  mutate(Day = ifelse(Day == 'D0', "Early", "Late"))

# TPM nomr count Not multimapping reads
#tpm_notmulti <- read_tsv(here("data", "gene_expression", 
#                              "counts_NOTmultimapping_TPM.tsv"))

# CPM Not multimapping
#cpm_notmulti <- read_tsv(here("data", "gene_expression", 
#                              "counts_NOTmultimapping_CPM.tsv"))

# TMM Not multimapping
tmm_notmulti <- read_tsv(here("data", "gene_expression", '98libs',
                              "counts_NOTmultimapping_TMM_allGenes.tsv"))


# TPM counts multimapping reads
#tpm_multi <- read_tsv(here("data", "gene_expression", 
#                           "counts_multimapping_TPM.tsv"))

gmt.reactn <- read_gmt(here("data", "reactome_data", 
                            "ReactomePathwaysLevel3_2021-03.gmt"))

#gmt.react <- read.gmt(gmtfile = here("data", "ReactomePathwaysLevel3.gmt"))
#gmt.btm <- read.gmt(gmtfile = here("data","BTM_for_GSEA_20131008.gmt"))

#int_fname <- system.file("extdata", "interactions.tsv", package = "CEMiTool")
#int_df <- read.delim(int_fname)

int_df <- read_tsv(here("data", "interaction_DB", 
                        "9606.gene.physical.links.STRINGv11_HGNC.tsv")) %>% 
  as.data.frame()
```

```{r Run CEMiTool NOT Multimapping}
smpl.annot <- pheno %>% 
  dplyr::select(Sample, Class, Day) %>% 
  unite("Class", Class:Day) %>% 
  dplyr::rename(SampleName = Sample) %>% 
  mutate(SampleName = as.character(SampleName))%>% 
  mutate(Class = factor(Class, levels = c("nonChronic_Early", 
                                             "nonChronic_Late",
                                             "Chronic_Early", "Chronic_Late")))

# TPM
counts <- as.data.frame(tpm_notmulti[!duplicated(tpm_notmulti$GeneSymbol),])
rownames(counts) <- counts$GeneSymbol

cem.reactome <- cemitool(expr = counts[,-c(1:2)], annot = smpl.annot, 
                         gmt = gmt.reactn, interactions = int_df, apply_vst = T, 
                         gsea_max_size = 2e3, verbose = TRUE)

cem.btm <- cemitool(expr = counts[,-c(1:2)], annot = smpl.annot, 
                    gmt = gmt.btm, interactions = int_df, apply_vst = T, 
                    gsea_max_size = 2e3, verbose = TRUE)

# Reactome TPM
generate_report(cem.reactome, title = "notMultimapping_Reactome_HGNC_TPM",
                directory = here("results", "CEMiTool", "Report",
                                 "notMultimapping_Reactome_HGNC_TPM"))
diagnostic_report(cem.reactome, title = "notMultimapping_Reactome_HGNC_TPM",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "notMultimapping_Reactome_HGNC_TPM"))
save_plots(cem.reactome, "all", 
           directory = here("results", "CEMiTool", "Plots",
                            "notMultimapping_Reactome_HGNC_TPM"))

# BTM TPM
generate_report(cem.btm, title = "notMultimapping_BTM",
                directory = here("results", "CEMiTool", "Report",
                                 "notMultimapping_BTM"))
diagnostic_report(cem.btm, title = "notMultimapping_BTM",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "notMultimapping_BTM"))
save_plots(cem.btm, "all", directory = here("results", "CEMiTool", "Plots",
                                            "notMultimapping_BTM"))


# Reactome CPM
cpm.counts <- as.data.frame(cpm_notmulti[!duplicated(cpm_notmulti$GeneSymbol),])
rownames(cpm.counts) <- cpm.counts$GeneSymbol

cem.reactome.cpm <- cemitool(expr = cpm.counts[,-c(1:2)], annot = smpl.annot, 
                         gmt = gmt.reactn, interactions = int_df, apply_vst = T, 
                         gsea_max_size = 2e3, verbose = TRUE)

generate_report(cem.reactome.cpm, title = "notMultimapping_Reactome_HGNC_CPM",
                directory = here("results", "CEMiTool", "Report",
                                 "notMultimapping_Reactome_HGNC_CPM"), force = T)
diagnostic_report(cem.reactome.cpm, title = "notMultimapping_Reactome_HGNC_CPM",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "notMultimapping_Reactome_HGNC_CPM"), force= T)
save_plots(cem.reactome.cpm, "all", 
           directory = here("results", "CEMiTool", "Plots",
                            "notMultimapping_Reactome_HGNC_CPM"), force = T)

# Reactome TMM
# Remove duplicated genes in GeneSymbol by taking the most expressed
tmm.counts <- tmm_notmulti %>% 
  dplyr::select(-gene_id, -Class) %>% 
  mutate(meanexpr = rowMeans(across(where(is.numeric)))) %>% 
  group_by(GeneSymbol) %>% 
  slice_max(meanexpr, with_ties = F) %>% 
  select(-meanexpr) %>% 
  column_to_rownames("GeneSymbol") %>% 
  as.data.frame()

cem.reactome.tmm <- cemitool(expr = tmm.counts, annot = smpl.annot, 
                         gmt = gmt.reactn, interactions = int_df, 
                         apply_vst = T, gsea_max_size = 2e3, verbose = TRUE)

generate_report(cem.reactome.tmm, title = "notMultimapping_Reactome3_HGNC_TMM",
                directory = here("results", "CEMiTool", "Report",
                                 "notMultimapping_Reactome_HGNC_TMM_98libs"))
diagnostic_report(cem.reactome.tmm, title = "notMultimapping_Reactome3_HGNC_TMM",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "notMultimapping_Reactome_HGNC_TMM_98libs"))
save_plots(cem.reactome.tmm, "all", 
           directory = here("results", "CEMiTool", "Plots",
                            "notMultimapping_Reactome_HGNC_TMM_98libs"))
```

```{r CEMiTool Multimapping}
smpl.annot <- pheno %>% 
  select(Sample, Class, Day) %>% 
  unite("Class", Class:Day) %>% 
  rename(SampleName = Sample) %>% 
  mutate(SampleName = as.character(SampleName))

counts <- as.data.frame(tpm_multi[!duplicated(tpm_multi$GeneSymbol),])
rownames(counts) <- counts$GeneSymbol

cem.reactome <- cemitool(expr = counts[,-c(1:2)], annot = smpl.annot, 
                         gmt = gmt.react, interactions = int_df, apply_vst = T, 
                         force_beta = T, gsea_max_size = 2e3, verbose = TRUE)

cem.btm <- cemitool(expr = counts[,-c(1:2)], annot = smpl.annot, 
                    gmt = gmt.btm, interactions = int_df, apply_vst = T, 
                    force_beta = T, gsea_max_size = 2e3, verbose = TRUE)

# Reactome
generate_report(cem.reactome, title = "Multimapping_Reactome",
                directory = here("results", "CEMiTool", "Report",
                                 "Multimapping_Reactome"))
diagnostic_report(cem.reactome, title = "Multimapping_Reactome",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "Multimapping_Reactome"))
save_plots(cem.reactome, "all", directory = here("results", "CEMiTool", "Plots",
                                                 "Multimapping_Reactome"))

# BTM
generate_report(cem.btm, title = "Multimapping_BTM",
                directory = here("results", "CEMiTool", "Report",
                                 "Multimapping_BTM"))
diagnostic_report(cem.btm, title = "Multimapping_BTM",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "Multimapping_BTM"))
save_plots(cem.btm, "all", directory = here("results", "CEMiTool", "Plots",
                                            "Multimapping_BTM"))
```

```{r Run TEST CEMiTool NOT Multimapping - reactome level 3 new}
smpl.annot <- pheno %>% 
  select(Sample, Class, Day) %>% 
  unite("Class", Class:Day) %>% 
  rename(SampleName = Sample) %>% 
  mutate(SampleName = as.character(SampleName))

counts <- as.data.frame(tpm_notmulti)
rownames(counts) <- counts$Symbol

cem.reactome <- cemitool(expr = counts[,-c(1:2)], annot = smpl.annot, 
                         gmt = gmt.reactn, apply_vst = T, interactions = int_df,
                         gsea_max_size = 2e3, verbose = TRUE)

# Reactome New (2021-02)
generate_report(cem.reactome, title = "notMultimapping_Reactome_new",
                directory = here("results", "CEMiTool", "Report",
                                 "notMultimapping_Reactome_new"))
diagnostic_report(cem.reactome, title = "notMultimapping_Reactome_new",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "notMultimapping_Reactome_new"))
save_plots(cem.reactome, "all", directory = here("results", "CEMiTool", "Plots",
                                                 "notMultimapping_Reactome_new"))
```

```{r Run TEST CEMiTool Multimapping - reactome level 3 new}
smpl.annot <- pheno %>% 
  select(Sample, Class, Day) %>% 
  unite("Class", Class:Day) %>% 
  rename(SampleName = Sample) %>% 
  mutate(SampleName = as.character(SampleName))

counts <- as.data.frame(tpm_multi)
rownames(counts) <- counts$Symbol

cem.reactome <- cemitool(expr = counts[,-c(1:2)], annot = smpl.annot, 
                         gmt = gmt.reactn, apply_vst = T, set_beta = 20,
                         gsea_max_size = 2e3, interactions = int_df,
                         verbose = TRUE)

# Reactome New (2021-02)
generate_report(cem.reactome, title = "Multimapping_Reactome_new",
                directory = here("results", "CEMiTool", "Report",
                                 "Multimapping_Reactome_new"))
diagnostic_report(cem.reactome, title = "Multimapping_Reactome_new",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "Multimapping_Reactome_new"))
save_plots(cem.reactome, "all", directory = here("results", "CEMiTool", "Plots",
                                                 "Multimapping_Reactome_new"))
```
