---
title: "Arbobios + CSBL CEMiTool"
editor_options: 
  chunk_output_type: console
---

```{r Load libraries}
library(here)
library(tidyverse)
library(CEMiTool)
```

```{r Load files}
counts <- read_tsv(here("data", "gene_expression",
                        "counts_Arbobios_CSBL_NOTmultimapping_TMM_allGenes.tsv"))

pheno <- read_tsv(here("data", "Arbobios_CSBL_CHIKV_phenodata.tsv"))

gmt.reactn <- read_gmt(here("data", "reactome_data", 
                            "ReactomePathwaysLevel3_2021-03.gmt"))

int_df <- read_tsv(here("data", "interaction_DB", 
                        "9606.gene.physical.links.STRINGv11_HGNC.tsv")) %>% 
  as.data.frame()
```

```{r CEMiTool}
annot <- pheno %>% 
  dplyr::select(Run, condition, phase, dataset, disease.status) %>% 
  mutate(phase = ifelse(is.na(phase) == T, "healthy", phase)) %>% 
  mutate(disease.status = case_when(phase == "healthy" ~ "healthy", 
                                    phase != 'healthy' &
                                    is.na(disease.status) ~ 'unknown',
                                    TRUE ~ disease.status)) %>% 
  column_to_rownames('Run')

smpl.annot <- annot %>%
  rownames_to_column("SampleName") %>% 
  select(SampleName, Class = phase)

tmm.counts <- counts %>% 
  select(-gene_id, -Class) %>% 
  mutate(meanexpr = rowMeans(across(where(is.numeric)))) %>% 
  group_by(GeneSymbol) %>% 
  slice_max(meanexpr, with_ties = F) %>% 
  select(-meanexpr) %>% 
  column_to_rownames("GeneSymbol") %>% 
  as.data.frame()

#cpm.counts.adj.hgnc <- cpm.counts.adj %>% 
#  as.data.frame() %>% 
#  rownames_to_column("gene_id") %>% 
#  inner_join(hannot %>% dplyr::select(gene_id, GeneSymbol)) %>% 
#  filter(!duplicated(GeneSymbol)) %>% 
#  dplyr::select(-gene_id) %>% 
#  column_to_rownames("GeneSymbol")

cem.reactome.tmm <- cemitool(expr = tmm.counts, 
                         annot = smpl.annot, apply_vst = T,
                         gmt = gmt.reactn, interactions = int_df, 
                         gsea_max_size = 2e3, verbose = TRUE)

#cem.reactome.cpm <- cemitool(expr = cpm.counts.adj.hgnc, 
#                         annot = smpl.annot, apply_vst = T,
#                         gmt = gmt.reactn, interactions = int_df, 
#                         gsea_max_size = 2e3, verbose = TRUE)

# TMM
generate_report(cem.reactome.tmm, title = "CSBL_Arbobios_integration TMM",
                directory = here("results", "CEMiTool", "Report",
                                 "CSBL_Arbobios_integration_TMM"))
diagnostic_report(cem.reactome.tmm, title = "CSBL_Arbobios_integration TMM",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "CSBL_Arbobios_integration_TMM"))
save_plots(cem.reactome.tmm, "all", 
           directory = here("results", "CEMiTool", "Plots",
                            "CSBL_Arbobios_integration TMM"))

# CPM
#generate_report(cem.reactome.cpm, title = "CSBL_Arbobios_integration CPM",
#                directory = here("results", "CEMiTool", "Report",
#                                 "CSBL_Arbobios_integration_CPM"), force = T)
#diagnostic_report(cem.reactome.cpm, title = "CSBL_Arbobios_integration CPM",
#                  directory = here("results", "CEMiTool", "Diagnostic",
#                                   "CSBL_Arbobios_integration_CPM"), force = T)
#save_plots(cem.reactome.cpm, "all", 
#           directory = here("results", "CEMiTool", "Plots",
#                            "CSBL_Arbobios_integration CPM"), force = T)
```

```{r 5 groups}
smpl.annot.5g <- annot %>% 
  filter(disease.status != "unknown") %>% 
  mutate(Class = ifelse(disease.status == "healthy", 
                     "healthy", paste(phase, disease.status, sep = "_"))) %>% 
  rownames_to_column("SampleName") %>% 
  select(SampleName, Class)

tmm.counts.5g <- tmm.counts %>% 
  select(smpl.annot.5g$SampleName)

cem.reactome.tmm <- cemitool(expr = tmm.counts.5g, 
                         annot = smpl.annot.5g, apply_vst = T,
                         gmt = gmt.reactn, interactions = int_df, 
                         gsea_max_size = 2e3, verbose = TRUE)

generate_report(cem.reactome.tmm, title = "CSBL_Arbobios_integration TMM_5g",
                directory = here("results", "CEMiTool", "Report",
                                 "CSBL_Arbobios_integration_TMM_5g"))
diagnostic_report(cem.reactome.tmm, title = "CSBL_Arbobios_integration TMM_5g",
                  directory = here("results", "CEMiTool", "Diagnostic",
                                   "CSBL_Arbobios_integration_TMM_5g"))
save_plots(cem.reactome.tmm, "all", 
           directory = here("results", "CEMiTool", "Plots",
                            "CSBL_Arbobios_integration TMM_5g"))
```

