---
title: "Extract third level Reactome pathways"
editor_options: 
  chunk_output_type: console
---

```{r Load libraries}
library(here)
library(tidyverse)
library(igraph)
library(ActivePathways)
```

```{r Load files}
# All levels of the pathway hierarchy (all organisms)
reactome_all <- read_tsv(here("data", "reactome_data", 
                              "Ensembl2Reactome_All_Levels.txt"), col_names = F)

# 27 top levels nodes
tln <- read_tsv(here("data", "reactome_data", "topLevel_nodes_reactome.txt"))

# Pathways hierarchy relationship
hch <- read_tsv(here("data", "reactome_data", "ReactomePathwaysRelation.txt"),
                col_names = F)

# Reactome pathways gmt
react.gmt <- read.GMT(here("data", "reactome_data", 
                           "ReactomePathways_20210317.gmt"))
```

```{r Get third level nodes}
hrel <- hch %>% 
  filter(grepl("HSA", X1))%>% 
  dplyr::rename(source = "X1", target = "X2")

# Calculate hierarchy level with graph.data.frame function from igraph pkg
graph_hrel <- graph.data.frame(hrel)

# Function to extract third level nodes based on 27 top nodes from "tln"
getlevel <- function(x) {
  level <- data.frame(node = names(shortest.paths(graph_hrel)[,x]), 
                     rank = shortest.paths(graph_hrel)[,x]+1)
  return(rownames(level[level$rank == 3, ]))
}

third_level <- unique(unlist(apply(as.data.frame(tln), 1, getlevel)))
```

```{r Filter third level nodes}
# Ensembl2reactome
gmt <- reactome_all %>%
  filter(X2 %in% third_level) %>% 
  filter(grepl("ENSG", X1)) %>% 
  dplyr::select(term = X4, gene = X1)

#write_tsv(gmt, here("data","reactome_data",
#                    "ReactomePathwaysLevel3_ensembl_2021-02.tsv"))

# GMT Objet
third_level_gmt <- Filter(function(term) term$name %in% third_level, react.gmt)

write.GMT(third_level_gmt, here("data", "reactome_data",
                                "ReactomePathwaysLevel3_2021-03.gmt"))

```

```{r Reactome tree structure}
hrel <- hch %>% 
  filter(grepl("HSA", X1))%>% 
  dplyr::rename(source = "X1", target = "X2")

# Calculate hierarchy level with graph.data.frame function from igraph pkg
graph_hrel <- graph.data.frame(hrel)

leaves <- which(degree(graph_hrel, v = V(graph_hrel), 
                       mode = "out") == 0, useNames = T)

root <- which(degree(graph_hrel, v = V(graph_hrel), 
                     mode = "in") == 0, useNames = T)

leaves.list <- list()
for (i in 1:length(root)) {
  node <- all_simple_paths(graph_hrel, from = root[i], to = leaves)
  for (j in 1:length(node)) {
    leaves.list[[rev(as_ids(node[[j]]))[1]]] <- as_ids(node[[j]])
  }

}

reactome_df <- plyr::ldply(leaves.list, rbind)

third_level <- reactome_df %>% 
  dplyr::select("3") %>% 
  na.omit() %>% 
  unique() %>%
  deframe

# GMT Objet
third_level_gmt <- Filter(function(term) term$name %in% third_level, react.gmt)

write.GMT(third_level_gmt, here("data", "reactome_data",
                                "ReactomePathwaysLevel3_2021-03.gmt"))

df <- NULL
for(k in third_level){
  root_node <- leaves.list[grep(k, leaves.list)][[1]][1]
  df <- rbind(df, data.frame(root = root_node, node = k))
}

out.df <- df %>%
  left_join(reactome_all %>% 
              select(X2, X4) %>% 
              unique(), by =c('root' = 'X2')) %>% 
  rename('root_name' = X4) %>% 
  left_join(reactome_all %>% 
              select(X2, X4) %>% 
              unique(), by =c('node' = 'X2')) %>% 
  rename('node_name' = X4) %>% 
  relocate(root, root_name, node, node_name)

#write_tsv(out.df, here("data", "reactome_data", 
#                       "ReactomePathways_leave_root_third_level.tsv"))
```

